---
title: ""

output: html_document
---

```{r setup, include=FALSE}
#############################################
############  summary
###########   american marten
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rmarkdown)
library(knitr)
library(kableExtra)
library(gridExtra)
library(logspline)


in.path<-"./_data/2018"
in.files<-list.files(in.path)
file.paths<-file.path(in.path, in.files)

significance.table<-tibble(covs = rep(NA, 6))
# significance.table$covs<-c('lure', 'snow', 'temp', 'pass', 'snow*temp', 'lure*snow')

## inline render
#
render.file<-'./_childRds/_CovDensitySum_child.Rmd'

# join <- function(ls, sep = ", "){
#     do.call(paste, append(ls, list(sep = sep)))
# }
# 
# 
# 
# inline_render <- function(script_name, .params){
#     suppressMessages(capture.output(rmarkdown::render(script_name, 
#                                                       output_format = "rmarkdown::md_document",
#                                                       params = .params), 
#                                     file = "tmp"))
#     cat(join(readLines(paste0(script_name, ".md")), "\n"))
# 
# }
```

```{r include = F}



in.file<-in.files[1]
sum.dat<-readRDS(file.path(in.path, in.file))
parameters<-sum.dat$parameter.summary
waic<-sum.dat$waic.table
meta<-sum.dat$meta.table


models.print<-waic %>% 
  select(model, description)

sum.dat$meta.table$sp


covs<- parameters %>% 
  filter(!is.na(Mean.rev.int.un)) %>% 
  select(covs) %>% 
  unique()

## run once
significance.table$covs <- unlist(covs)
density.out<-parameters %>% 
  select(model, covs, n_effective, mode, hdi_89pct_lower,hdi_89pct_upper) %>% 
  slice(c(1)) %>% 
  mutate(species = NA) %>% 
  slice(-1)%>% 
  select(species, everything())
# rm(significance.table)

### get species
species <- file.path(in.path, in.files) %>%
  map(readRDS)
species<-unlist(lapply(species, function(x) x$meta.table$sp))

#
#render.file<-'./_2019CovDensitySum_child.Rmd'

```

<br><br><br><br><br>

### Parameter summaries and model selection


**Models evaluated:**

*********************************************************************************************
```{r echo = F}
### models for the top of the page, before species tabs
kable(models.print,align = 'l') %>%
  kable_styling(bootstrap_options = "striped", full_width = F, position = "left")
```

<br><br><br>





##  {.tabset}



### `r i = 1; species[i]`

```{r, echo = F}
  in.file <- file.paths[i]
  sig.models <-  c("sc.fm1")
  support.tab<-tibble(level = c('good', 'moderate', 'poor'),
                    support = c('pval and rev MCMC', 'pval or rev MCMC', 'neither'),
                    covariates =  c('', 
                                    '', 
                                    'lure - snow - temp - pass - snow\\*temp - lure\\*snow'))
  #                                   lure, snow, temp, pass, snow*temp, lure*snow'
  significance.table[[species[i]]]<-c(F,     F,   F,    F,    F,          F)
```
```{r, child = render.file, as.is = T}

```

<br><br>

**notes:**

*********************************************************************************************************************************



***************************************************************************************************************




### `r i = 2; species[i]`

```{r, echo = F}
  in.file <- file.paths[i]
  sig.models <-  c("sc.fm1")
  support.tab<-tibble(level = c('good', 'moderate', 'poor'),
                    support = c('pval and rev MCMC', 'pval or rev MCMC', 'neither'),
                    covariates =  c('', 
                                    '', 
                                    'lure - snow - temp - pass - snow\\*temp - lure\\*snow'))
 #                                   lure, snow, temp, pass, snow*temp, lure*snow'
  significance.table[[species[i]]]<-c(F,     F,   F,    F,    F,          F)
```
```{r, child = render.file, as.is = T}

```

<br><br>

**notes:**

*********************************************************************************************************************************



***************************************************************************************************************


### `r i = 3; species[i]`

```{r, echo = F}
  in.file <- file.paths[i]
  sig.models <-  c("sc.fm1")
  support.tab<-tibble(level = c('good', 'moderate', 'poor'),
                    support = c('pval and rev MCMC', 'pval or rev MCMC', 'neither'),
                    covariates =  c('', 
                                    '', 
                                    'lure - snow - temp - pass - snow\\*temp - lure\\*snow'))
  #                                   lure, snow, temp, pass, snow*temp, lure*snow'
  significance.table[[species[i]]]<-c(F,     F,   F,    F,    F,          F)
```
```{r, child = render.file, as.is = T}

```

<br><br>

**notes:**

*********************************************************************************************************************************



***************************************************************************************************************



### `r i = 4; species[i]`

```{r, echo = F}
  in.file <- file.paths[i]
  sig.models <-  c("sc.fm1")
  support.tab<-tibble(level = c('good', 'moderate', 'poor'),
                    support = c('pval and rev MCMC', 'pval or rev MCMC', 'neither'),
                    covariates =  c('', 
                                    '', 
                                    'lure - snow - temp - pass - snow\\*temp - lure\\*snow'))
 #                                   lure, snow, temp, pass, snow*temp, lure*snow'
  significance.table[[species[i]]]<-c(F,     F,   F,    F,    F,          F)
```
```{r, child = render.file, as.is = T}

```

<br><br>

**notes:**

*********************************************************************************************************************************



***************************************************************************************************************



### `r i = 5; species[i]`

```{r, echo = F}
  in.file <- file.paths[i]
  sig.models <-  c("sc.fm1")
  support.tab<-tibble(level = c('good', 'moderate', 'poor'),
                    support = c('pval and rev MCMC', 'pval or rev MCMC', 'neither'),
                    covariates =  c('', 
                                    '', 
                                    'lure - snow - temp - pass - snow\\*temp - lure\\*snow'))
 #                                   lure, snow, temp, pass, snow*temp, lure*snow'
  significance.table[[species[i]]]<-c(F,     F,   F,    F,    F,          F)
```
```{r, child = render.file, as.is = T}

```

<br><br>

**notes:**

*********************************************************************************************************************************



***************************************************************************************************************



### `r i = 6; species[i]`

```{r, echo = F}
  in.file <- file.paths[i]
  sig.models <-  c("sc.fm1")
  support.tab<-tibble(level = c('good', 'moderate', 'poor'),
                    support = c('pval and rev MCMC', 'pval or rev MCMC', 'neither'),
                    covariates =  c('', 
                                    '', 
                                    'lure - snow - temp - pass - snow\\*temp - lure\\*snow'))
 #                                   lure, snow, temp, pass, snow*temp, lure*snow'
  significance.table[[species[i]]]<-c(F,     F,   F,    F,    F,          F)
```
```{r, child = render.file, as.is = T}

```

<br><br>

**notes:**

*********************************************************************************************************************************



***************************************************************************************************************


### `r i = 7; species[i]`

```{r, echo = F}
  in.file <- file.paths[i]
  sig.models <-  c("sc.fm1")
  support.tab<-tibble(level = c('good', 'moderate', 'poor'),
                    support = c('pval and rev MCMC', 'pval or rev MCMC', 'neither'),
                    covariates =  c('', 
                                    '', 
                                    'lure - snow - temp - pass - snow\\*temp - lure\\*snow'))
 #                                   lure, snow, temp, pass, snow*temp, lure*snow'
  significance.table[[species[i]]]<-c(F,     F,   F,    F,    F,          F)
```
```{r, child = render.file, as.is = T}

```

<br><br>

**notes:**

*********************************************************************************************************************************



***************************************************************************************************************


```{r, echo = F}
## output tables:
# saveRDS(density.out, file.path('./_data', paste(meta$year, 'density_sigCov_species.RDS', sep = '_')))
# saveRDS(significance.table, file.path('./_data', paste(meta$year, 'cov_significanceBySp.RDS', sep = '_')))

```
